version: "3.1"
services:
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: group7
      MYSQL_USER: group7
      MYSQL_PASSWORD: agent007
      MYSQL_ROOT_PASSWORD: agent007
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
